# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b3f70b6f940a3274b7a4337beaff6a70dd0e26560b01872f3e17c948f6e1903685fd771f2d217354ed69dfe9fe9d331ac12fd606c81b7d4378b5e269f315d750

test:
  secret_key_base: 9cf4f7ff1d0ec3a0b6c0a1478813ebdef2302805132a61c8627c3b787776880f7bafadff691631ed8343957b76565a905e7981ef585325ccf57c8f3575c84803

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
